# Generated by Django 5.2.12 on 2026-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('S', 'STARTED'), ('P', 'IN PROGRESS'), ('D', 'DONE')], default='S', max_length=1),
        ),
    ]
