# Generated by Django 5.2.12 on 2026-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_board', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('S', 'STARTED'), ('P', 'IN PROGRESS'), ('D', 'DONE'), ('O', 'OBSOLETE')], default='S', max_length=1),
        ),
    ]
